{{- $values := include "replicated.values" . | fromYaml -}}
{{- $global := default dict $values.global -}}
{{- $replicated := default dict (index $global "replicated") -}}
{{- if hasKey $replicated "dockerconfigjson" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "replicated.labels" . | nindent 4 }}
  {{- if $values.commonAnnotations }}
  annotations:
    {{- toYaml $values.commonAnnotations | nindent 4 }}
  {{- end }}
  name: enterprise-pull-secret
  namespace: {{ include "replicated.namespace" . | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $values.global.replicated.dockerconfigjson }}
{{- end }}
