apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "kots-sdk.labels" . | nindent 4 }}
  name: kots-sdk
spec:
  selector:
    matchLabels:
      {{- include "kots-sdk.selectorLabels" . | nindent 6 }}
  strategy:
    # this is to avoid having two sdk instances reporting at the same time for different app versions.
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "kots-sdk.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: kots-sdk
        image: {{ .Values.images.kotssdk }}
        imagePullPolicy: IfNotPresent
        env:
        - name: KOTS_SDK_LICENSE_BASE64
          value: {{ .Values.license | b64enc }}
        - name: KOTS_SDK_LICENSE_FIELDS_BASE64
          value: {{ .Values.licenseFields | b64enc }}
        - name: KOTS_SDK_CHANNEL_ID
          value: {{ .Values.channelID }}
        - name: KOTS_SDK_CHANNEL_NAME
          value: {{ .Values.channelName }}
        - name: KOTS_SDK_CHANNEL_SEQUENCE
          value: "{{ .Values.channelSequence }}"
        - name: KOTS_SDK_RELEASE_SEQUENCE
          value: "{{ .Values.releaseSequence }}"
        - name: KOTS_SDK_VERSION_LABEL
          value: "{{ .Values.versionLabel }}"
        - name: KOTS_SDK_INFORMERS_LABEL_SELECTOR
          value: ""
        - name: KOTS_SDK_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 100Mi
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: kots-sdk
status: {}
